"""Tests for FrontierReasoningPanel's provenance fixes (Phase 10 of the
exploration-pipeline-architecture refactor): the panel must describe WHO
actually detected/generated/allocated a frontier target using
candidate_input_mode, never inferring it from owns_target_generation or the
coordinator's name, and it must not claim "the coordinator generated the
frontier" for a plugin that only consumed a host-provided pool/cluster.
"""

from __future__ import annotations

from types import SimpleNamespace

from PySide6.QtWidgets import QApplication

from robotics_interfaces.plugins import CandidateInputMode, PluginRuntimeProfile
from robotics_sim.app.frontier_reasoning_panel import FrontierReasoningPanel


_app = QApplication.instance() or QApplication([])


def _profile(mode: CandidateInputMode) -> PluginRuntimeProfile:
    return PluginRuntimeProfile(
        detects_frontiers=mode is CandidateInputMode.PLUGIN_INTERNAL,
        generates_tasks=False,
        allocates_tasks=True,
        plans_paths=False,
        controls_motion=False,
        candidate_input_mode=mode,
    )


def _coordination_result():
    assignment = SimpleNamespace(
        robot_id=0,
        status="ASSIGNED",
        proposal=SimpleNamespace(
            source="host_frontier_candidate_pipeline",
            information_gain=3.0,
            metadata={"frontier_size": 5},
        ),
    )
    return SimpleNamespace(
        targets=((4.0, 4.0),),
        reasons=("selected",),
        assignments=(assignment,),
    )


def test_host_candidates_mode_does_not_claim_the_coordinator_generated_the_frontier():
    panel = FrontierReasoningPanel()

    panel.update_coordination(
        planner="Nearest frontier",
        coordinator="MMPF explore coordinator",
        result=_coordination_result(),
        robot_index=0,
        time_s=1.0,
        runtime_profile=_profile(CandidateInputMode.HOST_CANDIDATES),
        robot_positions=((0.0, 0.0),),
    )

    formula_text = panel.formula.text()
    assert "generated the candidate pool" in formula_text
    assert "generated the frontier" not in formula_text.lower()
    assert "Fᵢ* is generated by the active coordinator plugin" not in formula_text


def test_host_frontier_clusters_mode_says_host_detected_clusters():
    panel = FrontierReasoningPanel()

    panel.update_coordination(
        planner="Nearest frontier",
        coordinator="Frontier Cluster Hungarian",
        result=_coordination_result(),
        robot_index=0,
        time_s=1.0,
        runtime_profile=_profile(CandidateInputMode.HOST_FRONTIER_CLUSTERS),
        robot_positions=((0.0, 0.0),),
    )

    assert "detected frontier clusters" in panel.formula.text()


def test_plugin_internal_mode_does_not_show_the_configured_planner_formula():
    """The panel must not substitute the single-robot exploration_planner
    formula for a PLUGIN_INTERNAL algorithm -- planner_name has no effect on
    its (self-contained) candidate generation."""
    panel = FrontierReasoningPanel()

    panel.update_coordination(
        planner="Utility frontier",
        coordinator="Nav2D multi-wavefront coordinator",
        result=_coordination_result(),
        robot_index=0,
        time_s=1.0,
        runtime_profile=_profile(CandidateInputMode.PLUGIN_INTERNAL),
        robot_positions=((0.0, 0.0),),
    )

    formula_text = panel.formula.text()
    assert "internal to" in formula_text
    # The Utility-frontier single-robot formula's symbolic form must not appear.
    assert "0.75 d(R,F)" not in formula_text


def test_hybrid_mode_points_to_the_actual_source_used():
    panel = FrontierReasoningPanel()

    panel.update_coordination(
        planner="Nearest frontier",
        coordinator="FUEL frontier baseline coordinator",
        result=_coordination_result(),
        robot_index=0,
        time_s=1.0,
        runtime_profile=_profile(CandidateInputMode.HYBRID),
        robot_positions=((0.0, 0.0),),
    )

    assert "selected proposal source" in panel.substitution.text()
    assert "host_frontier_candidate_pipeline" in panel.substitution.text()


def test_legacy_integrated_mode_still_substitutes_the_single_robot_formula():
    """LEGACY_INTEGRATED is the one mode where the legacy per-robot scoring
    formula genuinely determined the score, so substituting it is correct."""
    panel = FrontierReasoningPanel()

    result = _coordination_result()
    panel.update_coordination(
        planner="Utility frontier",
        coordinator="NOIC information coordinator",
        result=result,
        robot_index=0,
        time_s=1.0,
        runtime_profile=_profile(CandidateInputMode.LEGACY_INTEGRATED),
        robot_positions=((0.0, 0.0),),
    )

    assert "0.75" in panel.formula.text() or "U(F)" in panel.formula.text()


def test_owns_target_generation_true_still_falls_back_correctly_without_candidate_input_mode():
    """Characterizes the previously-untested owns_target_generation=True
    branch with a bare profile stand-in that has no candidate_input_mode at
    all (the gap test_frontier_reasoning_panel.py's exploration noted)."""
    panel = FrontierReasoningPanel()

    panel.update_coordination(
        planner="Utility frontier",
        coordinator="Some plugin",
        result=_coordination_result(),
        robot_index=0,
        time_s=1.0,
        runtime_profile=SimpleNamespace(owns_target_generation=True),
        robot_positions=((0.0, 0.0),),
    )

    formula_text = panel.formula.text()
    assert "candidate_input_mode unavailable" in formula_text
    assert "0.75" not in formula_text
