"""
belief_trace_writer.py

Best-effort, file-based persistence for ROBOT_TRACE diagnostic events, so a
debugging session leaves a permanent record without shell redirection
(``python .\\main.py *>&1 | Tee-Object ...``). Given a run directory, writes:

    belief_events.jsonl        one JSON record per trace event (all categories)
    route_events.csv           one row per route attempt (ok/fail)
    frontier_events.csv        one row per frontier selection attempt
    decision_events.csv        one row per non-FOLLOW_PATH navigation decision
    obstacle_sections.csv      one row per grouped obstacle section
    route_affected_events.csv  one row per route_affected=yes occurrence
                                (throttled or repair-requested)
    run_summary.json           running counters, rewritten periodically
    belief_final.json          best-effort final/periodic belief-map snapshot

Pure output sink: never reads simulation state itself, never decides what
counts as an event -- robot_trace.py hands it already-computed data. Every
write is best-effort: any I/O failure disables the writer (after exactly one
warning via the `warn` callback) instead of raising into the simulation loop.

Belief-trace artifacts are generated by default, independent of
ROBOT_TRACE/terminal tracing -- BELIEF_TRACE_ARTIFACTS is the only env var
that can disable them (see robot_trace.py's RobotTrace.start_run()). The
default output directory is absolute and repo-root-based (REPO_ROOT below,
derived from this file's own location) so it never depends on the process's
current working directory; ROBOT_TRACE_DIR remains a supported override.
"""
from __future__ import annotations

import csv
import json
import time
from pathlib import Path
from typing import Callable

# robotics_sim/simulation/belief_trace_writer.py -> parents[2] is the repo root.
REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_BASE_DIR = str(REPO_ROOT / "runs" / "debug")

_CSV_COLUMNS: dict[str, tuple[str, ...]] = {
    "obstacle_sections": (
        "simulation_time", "robot_id", "orientation", "coord", "span_min",
        "span_max", "n_points", "raw_sample_count", "explored_percent",
    ),
    "route_events": (
        "simulation_time", "robot_id", "result", "reason", "start_x", "start_y",
        "goal_x", "goal_y", "waypoint_count", "length", "mapped_obs", "planner", "simplifier",
    ),
    "frontier_events": (
        "simulation_time", "robot_id", "source", "generated_count",
        "selected_x", "selected_y", "map_wide_fallback_used", "reason",
    ),
    "decision_events": (
        "simulation_time", "robot_id", "kind", "reason",
        "active_x", "active_y", "path_goal_x", "path_goal_y", "pending_x", "pending_y",
    ),
    "route_affected_events": (
        "simulation_time", "robot_id", "path_goal_x", "path_goal_y", "active_x", "active_y",
        "mapped_obs", "new_obstacle_count", "bbox_min_x", "bbox_min_y", "bbox_max_x", "bbox_max_y",
        "action",
    ),
}


def make_run_directory(base_dir: str = DEFAULT_BASE_DIR, *, now: float | None = None) -> Path:
    """Create (and return) a fresh timestamped run directory.

    Second-granularity timestamp is intentional (matches the required
    `belief_trace_YYYYMMDD_HHMMSS` naming); collisions within the same
    second are resolved by suffixing `_2`, `_3`, ... rather than raising.
    """
    timestamp = time.strftime("%Y%m%d_%H%M%S", time.localtime(now))
    base = Path(base_dir)
    candidate = base / f"belief_trace_{timestamp}"
    suffix = 1
    while candidate.exists():
        suffix += 1
        candidate = base / f"belief_trace_{timestamp}_{suffix}"
    candidate.mkdir(parents=True, exist_ok=True)
    return candidate


def _xy(point) -> tuple:
    if point is None:
        return ("", "")
    return (point[0], point[1])


class BeliefTraceWriter:
    """Best-effort file sink for one simulation run's ROBOT_TRACE events."""

    def __init__(self, run_dir, *, categories: tuple[str, ...] = (), warn: Callable[[str], None] | None = None):
        self.run_dir = Path(run_dir)
        self.categories = tuple(categories)
        self._warn = warn or (lambda message: None)
        self.enabled = True
        self._csv_has_header: set[str] = set()

        self.summary: dict = {
            "started_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
            "last_simulation_time": 0.0,
            "final_explored_percent": 0.0,
            "final_pose": None,
            "total_mapped_obstacles": 0,
            "total_route_ok": 0,
            "total_route_fail": 0,
            "route_fail_reasons": {},
            "total_frontier_selected": 0,
            "total_frontier_none": 0,
            "total_safety_replans": 0,
            "total_route_affected": 0,
            "last_exhaustion_reason": None,
            "trace_categories": list(self.categories),
        }
        self._writes_since_flush = 0
        self._write_summary()
        self._touch_expected_files()

    def _touch_expected_files(self) -> None:
        """Create every file the run directory is documented to contain
        (belief_events.jsonl + all 4 CSVs, each with its header row) up
        front, so the directory looks complete immediately after
        construction -- not only once a matching category happens to fire
        an event. Best-effort like everything else here."""
        if not self.enabled:
            return
        try:
            jsonl_path = self.run_dir / "belief_events.jsonl"
            if not jsonl_path.exists():
                jsonl_path.touch()
        except OSError as exc:
            self._disable(str(exc))
            return
        for name, columns in _CSV_COLUMNS.items():
            path = self.run_dir / f"{name}.csv"
            if path.exists():
                self._csv_has_header.add(name)
                continue
            try:
                with open(path, "w", newline="", encoding="utf-8") as f:
                    csv.DictWriter(f, fieldnames=list(columns)).writeheader()
                self._csv_has_header.add(name)
            except OSError as exc:
                self._disable(str(exc))
                return

    # ------------------------------------------------------------------ internals

    def _disable(self, reason: str) -> None:
        if not self.enabled:
            return
        self.enabled = False
        self._warn(f"[TRACE FILE] disabled after write error: {reason}")

    def _maybe_flush_summary(self) -> None:
        self._writes_since_flush += 1
        if self._writes_since_flush >= 10:
            self._writes_since_flush = 0
            self._write_summary()

    def _write_summary(self) -> None:
        if not self.enabled:
            return
        try:
            with open(self.run_dir / "run_summary.json", "w", encoding="utf-8") as f:
                json.dump(self.summary, f, indent=2, default=str)
        except OSError as exc:
            self._disable(str(exc))

    def _append_jsonl(self, record: dict) -> None:
        if not self.enabled:
            return
        try:
            with open(self.run_dir / "belief_events.jsonl", "a", encoding="utf-8") as f:
                f.write(json.dumps(record, default=str) + "\n")
        except OSError as exc:
            self._disable(str(exc))

    def _append_csv(self, name: str, row: dict) -> None:
        if not self.enabled:
            return
        columns = _CSV_COLUMNS[name]
        path = self.run_dir / f"{name}.csv"
        try:
            write_header = name not in self._csv_has_header and not path.exists()
            with open(path, "a", newline="", encoding="utf-8") as f:
                writer = csv.DictWriter(f, fieldnames=list(columns))
                if write_header:
                    writer.writeheader()
                writer.writerow({col: row.get(col, "") for col in columns})
            self._csv_has_header.add(name)
        except OSError as exc:
            self._disable(str(exc))

    # ------------------------------------------------------------------ event recording

    def record_event(
        self,
        event_type: str,
        *,
        simulation_time: float,
        robot_id: str = "R1",
        pose=None,
        explored_percent=None,
        mapped_obstacle_samples=None,
        payload: dict | None = None,
    ) -> None:
        """Append one line to belief_events.jsonl for any trace category."""
        if not self.enabled:
            return
        record: dict = {
            "event_type": event_type,
            "simulation_time": float(simulation_time),
            "robot_id": robot_id,
        }
        if pose is not None:
            record["pose"] = [float(pose[0]), float(pose[1])]
        if explored_percent is not None:
            record["explored_percent"] = float(explored_percent)
        if mapped_obstacle_samples is not None:
            record["mapped_obstacle_samples"] = int(mapped_obstacle_samples)
        record["payload"] = payload or {}
        self._append_jsonl(record)

        self.summary["last_simulation_time"] = float(simulation_time)
        if pose is not None:
            self.summary["final_pose"] = [float(pose[0]), float(pose[1])]
        if explored_percent is not None:
            self.summary["final_explored_percent"] = float(explored_percent)
        if mapped_obstacle_samples is not None:
            self.summary["total_mapped_obstacles"] = int(mapped_obstacle_samples)
        self._maybe_flush_summary()

    def record_obstacle_section(
        self,
        *,
        simulation_time: float,
        robot_id: str,
        orientation: str,
        coord: float,
        span_min: float,
        span_max: float,
        n_points: int,
        raw_sample_count: int,
        explored_percent,
    ) -> None:
        self._append_csv(
            "obstacle_sections",
            dict(
                simulation_time=simulation_time, robot_id=robot_id, orientation=orientation,
                coord=coord, span_min=span_min, span_max=span_max, n_points=n_points,
                raw_sample_count=raw_sample_count, explored_percent=explored_percent,
            ),
        )

    def record_route_event(
        self,
        *,
        simulation_time: float,
        robot_id: str,
        result: str,
        reason: str = "",
        start=None,
        goal=None,
        waypoint_count=None,
        length=None,
        mapped_obs: int = 0,
        planner: str = "",
        simplifier: str = "",
    ) -> None:
        start_x, start_y = _xy(start)
        goal_x, goal_y = _xy(goal)
        self._append_csv(
            "route_events",
            dict(
                simulation_time=simulation_time, robot_id=robot_id, result=result, reason=reason,
                start_x=start_x, start_y=start_y, goal_x=goal_x, goal_y=goal_y,
                waypoint_count=waypoint_count if waypoint_count is not None else "",
                length=length if length is not None else "", mapped_obs=mapped_obs,
                planner=planner, simplifier=simplifier,
            ),
        )
        self.summary["last_simulation_time"] = float(simulation_time)
        if result == "ok":
            self.summary["total_route_ok"] += 1
        else:
            self.summary["total_route_fail"] += 1
            reasons = self.summary["route_fail_reasons"]
            reasons[reason] = int(reasons.get(reason, 0)) + 1
        self._maybe_flush_summary()

    def record_frontier_event(
        self,
        *,
        simulation_time: float,
        robot_id: str,
        source: str,
        generated_count=None,
        selected=None,
        map_wide_fallback_used: bool = False,
        reason: str = "",
    ) -> None:
        selected_x, selected_y = _xy(selected)
        self._append_csv(
            "frontier_events",
            dict(
                simulation_time=simulation_time, robot_id=robot_id, source=source,
                generated_count=generated_count if generated_count is not None else "",
                selected_x=selected_x, selected_y=selected_y,
                map_wide_fallback_used=bool(map_wide_fallback_used), reason=reason,
            ),
        )
        self.summary["last_simulation_time"] = float(simulation_time)
        if selected is not None:
            self.summary["total_frontier_selected"] += 1
        else:
            self.summary["total_frontier_none"] += 1
            if reason:
                self.summary["last_exhaustion_reason"] = reason
        self._maybe_flush_summary()

    def record_decision_event(
        self,
        *,
        simulation_time: float,
        robot_id: str,
        kind: str,
        reason: str = "",
        active=None,
        path_goal=None,
        pending=None,
    ) -> None:
        active_x, active_y = _xy(active)
        path_goal_x, path_goal_y = _xy(path_goal)
        pending_x, pending_y = _xy(pending)
        self._append_csv(
            "decision_events",
            dict(
                simulation_time=simulation_time, robot_id=robot_id, kind=kind, reason=reason,
                active_x=active_x, active_y=active_y, path_goal_x=path_goal_x, path_goal_y=path_goal_y,
                pending_x=pending_x, pending_y=pending_y,
            ),
        )
        self.summary["last_simulation_time"] = float(simulation_time)
        if kind == "REPLAN_FOR_SAFETY":
            self.summary["total_safety_replans"] += 1
        self._maybe_flush_summary()

    def record_route_affected_event(
        self,
        *,
        simulation_time: float,
        robot_id: str = "R1",
        path_goal=None,
        active=None,
        mapped_obs: int = 0,
        new_obstacle_count: int = 0,
        bbox=None,
        action: str = "",
    ) -> None:
        """Every route_affected=yes occurrence (throttled or allowed) --
        the single place total_route_affected is incremented, so the
        counter and route_affected_events.csv's row count can never
        drift apart (see run_summary consistency requirements)."""
        path_goal_x, path_goal_y = _xy(path_goal)
        active_x, active_y = _xy(active)
        if bbox is not None:
            bbox_min_x, bbox_min_y, bbox_max_x, bbox_max_y = bbox
        else:
            bbox_min_x = bbox_min_y = bbox_max_x = bbox_max_y = ""
        self._append_csv(
            "route_affected_events",
            dict(
                simulation_time=simulation_time, robot_id=robot_id,
                path_goal_x=path_goal_x, path_goal_y=path_goal_y,
                active_x=active_x, active_y=active_y,
                mapped_obs=mapped_obs, new_obstacle_count=new_obstacle_count,
                bbox_min_x=bbox_min_x, bbox_min_y=bbox_min_y,
                bbox_max_x=bbox_max_x, bbox_max_y=bbox_max_y,
                action=action,
            ),
        )
        self.summary["last_simulation_time"] = float(simulation_time)
        self.summary["total_route_affected"] += 1
        self._maybe_flush_summary()

    def write_belief_snapshot(self, snapshot: dict) -> None:
        """Best-effort belief_final.json (+ belief_grid_final.npz when a
        raw grid array is cheaply available). `snapshot` may include an
        internal `_grid` numpy array key -- popped and never JSON-encoded.
        """
        if not self.enabled:
            return
        snapshot = dict(snapshot)
        grid = snapshot.pop("_grid", None)
        try:
            with open(self.run_dir / "belief_final.json", "w", encoding="utf-8") as f:
                json.dump(snapshot, f, indent=2, default=str)
        except OSError as exc:
            self._disable(str(exc))
            return
        if grid is not None:
            try:
                import numpy as np

                np.savez_compressed(self.run_dir / "belief_grid_final.npz", grid=grid)
            except OSError as exc:
                self._disable(str(exc))

    def flush_summary(self) -> None:
        self._write_summary()
